version: '3.8'

services:
  # Database Service
  db:
    image: postgres:15-alpine
    container_name: brainybite-new-db-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: brainy_bite
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: