# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
# Disable SQL visibility to avoid cluttering the server logs and prevent data leaks.
spring.jpa.show-sql=false

#URL AWS Cognito Mock
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_URL}

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

aws.s3.bucket-name=${S3_BUCKET_NAME}
aws.region=${AWS_REGION}
aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}

frontend.url=${FRONTEND_URL}