# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
# Disable SQL visibility to avoid cluttering the server logs and prevent data leaks.
spring.jpa.show-sql=false
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_URL}