name: Build and Push to ECR

on:
  push:
    branches: ["main"]
    paths:
      - "brainybite-new/**"
      - .github/workflows/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::108782062712:role/github-actions-ecr-role
          aws-region: ap-southeast-7

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: brainy-bite/backend
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./brainybite-new
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
